services:
  - type: web
    plan: free
    name: university-display-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: university_display.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        value: university_display_db
      - key: DB_USER
        value: university_display_db_user
      - key: DB_PASSWORD
        value: fpK8aElu1H9wwopYy4OtKanrpNqLPAwt
      - key: DB_HOST
        value: dpg-cvkuihs9c44c73dajtf0-a
      - key: DB_PORT
        value: 5432
