# Generated by Django 4.2.15 on 2025-04-22 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='السعة')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجدول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الجدول')),
                ('active', models.BooleanField(default=False, verbose_name='جدول نشط')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='المكان')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('available', models.BooleanField(default=True, verbose_name='هل الموعد متاح؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الموعد')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__iexact': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='الدكتور المسؤول')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكورس')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الكورس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الكورس')),
                ('num_students', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classrooms.classroom', verbose_name='القاعة')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__iexact': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='الدكتور المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_canceled', models.BooleanField(default=False, verbose_name='تم الإلغاء')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة الدكتور')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.course')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_schedules', to='classrooms.classschedule')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_schedules', to='classrooms.table')),
            ],
            options={
                'ordering': ['table', 'class_schedule__day', 'class_schedule__start_time'],
                'unique_together': {('table', 'class_schedule')},
            },
        ),
    ]
