# Generated by Django 4.2.15 on 2025-03-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجدول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الجدول')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.CreateModel(
            name='TableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_schedules', to='classrooms.classschedule')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_schedules', to='classrooms.table')),
            ],
            options={
                'ordering': ['table', 'class_schedule__day', 'class_schedule__start_time'],
                'unique_together': {('table', 'class_schedule')},
            },
        ),
    ]
