# Generated by Django 4.2.15 on 2025-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.CharField(default='', max_length=100, verbose_name='السعة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_students',
            field=models.CharField(default='', max_length=100, verbose_name='عدد الطلاب'),
        ),
    ]
