# Generated by Django 4.2.15 on 2025-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_table_alter_classschedule_options_tableschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='active',
            field=models.BooleanField(default=False, verbose_name='جدول نشط'),
        ),
    ]
