# Generated by Django 4.2.15 on 2025-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_table_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
