# Generated by Django 4.2.15 on 2025-04-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_doctorappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(default='شعبة عامة', max_length=100),
        ),
    ]
