# Generated by Django 4.2.15 on 2025-04-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='السعة'),
        ),
    ]
