# Generated by Django 4.2.15 on 2025-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_full_name_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
